export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const RESET_PARTY_REQUEST = "RESET_PARTY_REQUEST";
export const CONFIRM_PARTY_REQUEST = "CONFIRM_PARTY_REQUEST";